services: 
  fastapi-app-0:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: fastapi-app-0
    ports:
      - 8000:8000
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-batch-size: "100"
        max-size: "10m"
        max-file: "3"
        labels: "service=fastapi"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        labels: "service=prometheus"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-0
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        labels: "service=grafana"
    networks:
      - monitoring

  loki:
    image: grafana/loki:latest
    container_name: loki-0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  grafana_data: {}
  app_logs: {}

